### ISSUE TITLE
Locally running simulation

### ISSUE THREAD

**Issue by BladeTransformerLLC** [matsuoka-601/wasm-fluid-simulation#1]
Hi there!

I'd like to run simulations locally without using GitHub Workflows.

```
$ npm install
$ npm run build
```

I get the following error from the above command:

```
ERROR in ./pkg/snippets/wasm-bindgen-rayon-9d40dbf53d170728/src/workerHelpers.worker.js 22:0-60
Module not found: Error: Can't resolve '../../../' in '/mnt/d/src/wasm-fluid-simulation/pkg/snippets/wasm-bindgen-rayon-9d40dbf53d170728/src'
Did you mean 'rust_fluid.js'?
BREAKING CHANGE: The request '../../../' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
resolve '../../../' in '/mnt/d/src/wasm-fluid-simulation/pkg/snippets/wasm-bindgen-rayon-9d40dbf53d170728/src'
  Parsed request is a directory
  using description file: /mnt/d/src/wasm-fluid-simulation/pkg/package.json (relative path: ./snippets/wasm-bindgen-rayon-9d40dbf53d170728/src)
    Field 'browser' doesn't contain a valid alias configuration
 @ ./pkg/snippets/wasm-bindgen-rayon-9d40dbf53d170728/src/workerHelpers.js 42:21-47:7
 @ ./pkg/rust_fluid.js 1:0-99 613:20-32
 @ ./index.js

webpack 5.96.1 compiled with 1 error in 1009 ms
```

Thanks

**Comment by matsuoka-601** [comment]
Hello, thanks for having an interest in this project!

I haven't figured out the root cause of the error, but a workaround I recommend is that building the repo without webpack. I'll explain the steps. 

- Change `"build"` in `package.json` like below.
	- before: `"build": "cross-env RUSTUP_TOOLCHAIN=nightly wasm-pack build --target web && webpack build ./index.js --mode production -o dist --output-filename index.js && shx cp index.html dist/",`
	- after: `"build": "cross-env RUSTUP_TOOLCHAIN=nightly wasm-pack build --target web",`
- Change the code in `Cargo.toml` like below.
	- before: `wasm-bindgen-rayon = { version = "1.2" }`
	- after: `wasm-bindgen-rayon = { version = "1.2", features = ["no-bundler"] }`
- Change the code in `server.js` like below.
	- before: `app.use(express.static(__dirname + '/dist/'));`
	- after: `app.use(express.static(__dirname));`
- Remove the line `import { simd } from 'wasm-feature-detect';` in `index.js`

This is a bit dirty workaround, but probably works.

**Comment by BladeTransformerLLC** [comment]
Thanks, it worked!

The only thing I needed to do additionally in my environment (WSL2) was to remove all toolchains but nightly (otherwise I would get a strange error when compiling).

```
$ rustup toolchain list
nightly-x86_64-unknown-linux-gnu (override)
```

**Comment by matsuoka-601** [comment]
Glad to hear that! I'll also write on README about how to run the simulation without webpack.
